apiVersion: v1
kind: Service
metadata:
  name: dask-sql
spec:
  ports:
  - name: dask-sql
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: dask-sql
status:
  loadBalancer: {}
